[profile.default]
src = "src"
out = "out"
libs = ["lib"]
auto_detect_solc = true

# Enables or disables the optimizer
optimizer = true
# The number of optimizer runs
optimizer_runs = 200

# Print the names of the compiled contracts
names = true
# Print the sizes of the compiled contracts
sizes = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
